// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqxWcCZjYOsdfR9MOvTMI1aQTyBn24F5U',
    appId: '1:1013632939287:web:d91509cd3307130cc7f352',
    messagingSenderId: '1013632939287',
    projectId: 'hris-tetra',
    authDomain: 'hris-tetra.firebaseapp.com',
    storageBucket: 'hris-tetra.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7arHjR6skSQyXleBNuhVA2E8u4e8gy_I',
    appId: '1:1013632939287:android:bec9fe03430492d1c7f352',
    messagingSenderId: '1013632939287',
    projectId: 'hris-tetra',
    storageBucket: 'hris-tetra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQWK0-aDkJ-ASUPq6mKEWeR92KrtdqNE',
    appId: '1:1013632939287:ios:9112e23b3017f6dbc7f352',
    messagingSenderId: '1013632939287',
    projectId: 'hris-tetra',
    storageBucket: 'hris-tetra.firebasestorage.app',
    iosBundleId: 'com.example.mobileAbsensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByQWK0-aDkJ-ASUPq6mKEWeR92KrtdqNE',
    appId: '1:1013632939287:ios:9112e23b3017f6dbc7f352',
    messagingSenderId: '1013632939287',
    projectId: 'hris-tetra',
    storageBucket: 'hris-tetra.firebasestorage.app',
    iosBundleId: 'com.example.mobileAbsensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqxWcCZjYOsdfR9MOvTMI1aQTyBn24F5U',
    appId: '1:1013632939287:web:a7503aa8eb80b5d9c7f352',
    messagingSenderId: '1013632939287',
    projectId: 'hris-tetra',
    authDomain: 'hris-tetra.firebaseapp.com',
    storageBucket: 'hris-tetra.firebasestorage.app',
  );
}
